### ISSUE TITLE
Question - does the kafka chart re-use the etcd deployed by K8s

### ISSUE THREAD

**Issue by dkirrane** [banzaicloud/apache-kafka-on-k8s#6]
I have a kubeadm created cluster. Will the Kafka helm chart re-use the k8s cluster etcd?

Also, are both headless-service and service needed?

**Comment by baluchicken** [comment]
Hi @dkirrane, our helm chart will not re-use the k8s cluster etcd, it will create a new one with the etch-operator.
I just checked and you are right only the headless-service is required right now. I will remove it from the helm chart, or if you want PR's are welcome;)(https://github.com/banzaicloud/banzai-charts)

**Comment by baluchicken** [comment]
https://github.com/banzaicloud/banzai-charts/pull/210 This one removes the service from the chart.
